# Generated by Django 3.1.4 on 2020-12-04 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Условие')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Условие',
                'verbose_name_plural': 'Условии',
            },
        ),
        migrations.CreateModel(
            name='Method_survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Условие')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Метод',
                'verbose_name_plural': 'Методы',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Type_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название типа')),
                ('slug', models.SlugField(max_length=20)),
            ],
            options={
                'verbose_name': 'Тип ответа',
                'verbose_name_plural': 'Типы ответов',
            },
        ),
        migrations.CreateModel(
            name='Type_surveys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название типа')),
                ('slug', models.SlugField(max_length=20)),
            ],
            options={
                'verbose_name': 'Тип опроса',
                'verbose_name_plural': 'Типы опросов',
            },
        ),
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название опроса')),
                ('create', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('questions', models.ManyToManyField(related_name='survey', to='serveys.Questions', verbose_name='Вопрос')),
                ('type_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='serveys.type_surveys', verbose_name='Тип опроса')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.AddField(
            model_name='questions',
            name='type_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='serveys.type_answer', verbose_name='Тип ответа'),
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadlines_start', models.DateTimeField()),
                ('deadlines_stop', models.DateTimeField()),
                ('condition', models.ManyToManyField(related_name='parameter', to='serveys.Conditions', verbose_name='Условие')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='serveys.method_survey', verbose_name='Метод')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='serveys.surveys', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
    ]
